// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;

public class SuiteTests : IDisposable {
    public IWebDriver Driver {get; private set;}
    public IDictionary<String, Object> Vars {get; private set;}
    public IJavaScriptExecutor Js {get; private set;}

    public SuiteTests()
    {
      Driver = new ChromeDriver();
      Js = (IJavaScriptExecutor)Driver;
      Vars = new Dictionary<String, Object>();
    }

    public void Dispose()
    {
      Driver.Quit();
    }

    public void Berg() {
        Driver.Navigate().GoToUrl("https://www.discovercamping.ca/BCCWeb/Facilities/TrailRiverCampingSearchView.aspx");
        Driver.Manage().Window.Size = new System.Drawing.Size(1708, 920);
        Driver.FindElement(By.Id("ddlPlaces")).Click();
        {
          var dropdown = Driver.FindElement(By.Id("ddlPlaces"));
          dropdown.FindElement(By.XPath("//option[. = 'Berg Lake Trail']")).Click();
        }
        Driver.FindElement(By.Id("ddlPlaces")).Click();
        Driver.FindElement(By.Id("mainContent_homeContent_txtArrivalDate")).Click();
        Driver.FindElement(By.CssSelector(".ui-icon-circle-triangle-e")).Click();
        Driver.FindElement(By.CssSelector(".ui-icon-circle-triangle-e")).Click();
        Driver.FindElement(By.CssSelector(".ui-icon-circle-triangle-e")).Click();
        Driver.FindElement(By.CssSelector(".ui-icon-circle-triangle-e")).Click();
        Driver.FindElement(By.CssSelector(".ui-icon-circle-triangle-e")).Click();
        Driver.FindElement(By.CssSelector(".ui-icon-circle-triangle-e")).Click();
        {
          var element = Driver.FindElement(By.CssSelector(".ui-icon-circle-triangle-e"));
          Actions builder = new Actions(Driver);
          builder.MoveToElement(element).Perform();
        }
        Driver.FindElement(By.CssSelector(".ui-icon-circle-triangle-e")).Click();
        Driver.FindElement(By.LinkText("6")).Click();
        Driver.FindElement(By.Id("btnSearch")).Click();
        Driver.FindElement(By.Id("7")).Click();
        Driver.FindElement(By.Id("26")).Click();
    }
}